import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, FileText, Shield, AlertTriangle, Scale, Ban, CreditCard, RefreshCw, Globe, Gavel } from "lucide-react";
import logo from "@/assets/logo_obsidian_root.svg";

const lastUpdated = "February 13, 2026";

const sections = [
  {
    icon: FileText,
    title: "1. Acceptance of Terms",
    content: [
      "By accessing or using the Phishing D&P platform, you agree to be bound by these Terms of Service and our Privacy Policy.",
      "If you are using the platform on behalf of an organization (Enterprise account), you represent that you have the authority to bind that organization to these terms.",
      "If you do not agree with any part of these terms, you must not use the platform.",
      "We reserve the right to update these terms at any time. Continued use of the platform after changes constitutes acceptance of the updated terms.",
    ],
  },
  {
    icon: Shield,
    title: "2. Description of Service",
    content: [
      "Phishing D&P is a cybersecurity platform that provides AI-powered phishing detection and analysis tools, including email analysis, URL scanning, domain investigation, visual impersonation detection, and file attachment scanning.",
      "**User Accounts** provide access to all analysis modules, personal reports, and profile management features.",
      "**Enterprise Accounts** include all User features plus employee email management, organization-wide activity monitoring, threat reports for employee email and browsing activity, and administrative controls.",
      "The platform processes submitted content in real-time using machine learning models and threat intelligence databases to identify phishing attempts, malware, and suspicious activity.",
    ],
  },
  {
    icon: Scale,
    title: "3. User Responsibilities",
    content: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
      "You agree to provide accurate and complete information when registering and to keep your account information up to date.",
      "You must not use the platform to submit content that you do not have the right to analyze, or to conduct any illegal activity.",
      "Enterprise administrators are responsible for obtaining proper consent from employees before monitoring their email and browsing activity through the platform.",
      "You must not attempt to reverse-engineer, decompile, or extract the source code of our detection algorithms or AI models.",
    ],
  },
  {
    icon: Ban,
    title: "4. Prohibited Uses",
    content: [
      "Using the platform to create, distribute, or facilitate phishing attacks or any form of cybercrime.",
      "Submitting malicious content with the intent to test or bypass our detection systems for malicious purposes.",
      "Attempting to gain unauthorized access to other users' accounts, data, or the platform's infrastructure.",
      "Using automated tools (bots, scrapers) to access the platform without prior written authorization.",
      "Sharing your account credentials or allowing unauthorized third parties to access your account.",
      "Using Enterprise monitoring features to surveil employees without proper legal authorization and disclosure.",
    ],
  },
  {
    icon: Globe,
    title: "5. Intellectual Property",
    content: [
      "All content, features, and functionality of the Phishing D&P platform — including the detection algorithms, AI models, user interface, branding, and documentation — are owned by Phishing D&P and protected by intellectual property laws.",
      "You retain ownership of the content you submit for analysis (emails, URLs, files). By submitting content, you grant us a limited, temporary license to process it for analysis purposes only.",
      "Analysis reports generated by the platform may be downloaded, saved, and shared within your organization but may not be resold or commercially redistributed.",
    ],
  },
  {
    icon: CreditCard,
    title: "6. Account Types & Access",
    content: [
      "**User (Free):** Access to all analysis modules (email, URL, domain, visual, file, classification), personal dashboard, and profile settings.",
      "**Enterprise:** All User features plus employee management, organization-wide activity reports, security policy configuration, CSV export, and priority support.",
      "We reserve the right to modify feature availability, introduce usage limits, or offer premium tiers in the future with reasonable notice.",
      "Accounts that remain inactive for more than 12 months may be flagged for deletion with prior notification.",
    ],
  },
  {
    icon: AlertTriangle,
    title: "7. Limitation of Liability",
    content: [
      "Phishing D&P provides analysis results on a **best-effort basis**. While our AI models are trained on extensive threat data, no detection system is 100% accurate.",
      "We are not liable for any damages resulting from phishing attacks, malware infections, or data breaches that occur despite using our platform.",
      "The platform should be used as one layer of a comprehensive cybersecurity strategy, not as a sole defense mechanism.",
      "We do not guarantee uninterrupted or error-free service and are not liable for any losses caused by service downtime or technical issues.",
      "Enterprise activity reports reflect data as processed by our systems and should be verified before taking disciplinary or legal action against employees.",
    ],
  },
  {
    icon: RefreshCw,
    title: "8. Termination",
    content: [
      "You may terminate your account at any time through your Profile Settings or by contacting our support team.",
      "We reserve the right to suspend or terminate accounts that violate these terms, engage in prohibited activities, or pose a security risk to the platform.",
      "Upon termination, your account data will be permanently deleted within 30 days, except where retention is required by law.",
      "Enterprise administrators may remove individual employees from their organization at any time, which will delete the employee's associated activity data.",
    ],
  },
  {
    icon: Gavel,
    title: "9. Governing Law",
    content: [
      "These Terms of Service are governed by and construed in accordance with the laws of Algeria.",
      "Any disputes arising from these terms or the use of the platform shall be resolved through good-faith negotiation first, and if necessary, through the competent courts of Algiers, Algeria.",
      "If any provision of these terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.",
    ],
  },
];

const TermsOfService = () => (
  <div className="min-h-screen bg-background">
    {/* Header */}
    <header className="border-b border-border bg-card/50 backdrop-blur-lg sticky top-0 z-50">
      <div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2.5">
          <img src={logo} alt="Phishing D&P" className="w-7 h-7 object-contain" />
          <span className="font-bold text-sm">Phishing <span className="text-gradient">D&P</span></span>
        </Link>
        <Link to="/" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
      </div>
    </header>

    {/* Content */}
    <main className="max-w-4xl mx-auto px-4 py-12">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-10">
        {/* Title */}
        <div className="text-center space-y-3">
          <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto">
            <FileText className="w-7 h-7 text-primary" />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold">Terms of <span className="text-gradient">Service</span></h1>
          <p className="text-sm text-muted-foreground">Last updated: {lastUpdated}</p>
          <p className="text-sm text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Please read these Terms of Service carefully before using the Phishing D&P platform. 
            These terms outline your rights and responsibilities when using our phishing detection and cybersecurity analysis services.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section, i) => (
            <motion.section
              key={section.title}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              className="glass-card p-6 md:p-8 space-y-4"
            >
              <h2 className="text-lg font-bold flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <section.icon className="w-4 h-4 text-primary" />
                </div>
                {section.title}
              </h2>
              <ul className="space-y-3">
                {section.content.map((item, j) => (
                  <li key={j} className="text-sm text-muted-foreground leading-relaxed pl-4 border-l-2 border-primary/10">
                    {item.split(/(\*\*.*?\*\*)/).map((part, k) =>
                      part.startsWith("**") && part.endsWith("**") ? (
                        <strong key={k} className="text-foreground font-medium">{part.slice(2, -2)}</strong>
                      ) : (
                        <span key={k}>{part}</span>
                      )
                    )}
                  </li>
                ))}
              </ul>
            </motion.section>
          ))}
        </div>

        {/* Contact */}
        <div className="glass-card p-6 md:p-8 text-center space-y-3">
          <h2 className="text-lg font-bold">Questions?</h2>
          <p className="text-sm text-muted-foreground leading-relaxed max-w-xl mx-auto">
            If you have any questions about these Terms of Service, 
            please contact us at <span className="text-primary font-medium">legal@phishingdp.com</span>
          </p>
        </div>
      </motion.div>
    </main>
  </div>
);

export default TermsOfService;
